name: Namaskaaram 

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'
  # push:
  #   branches:
  #     - main


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
     - name: Hello world
       run: echo "Hello world"