# Generated by Django 5.0.6 on 2024-06-18 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_subscriptionprice_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionprice',
            options={'ordering': ['order', 'featured', '-updated']},
        ),
    ]
