# Generated by Django 5.0.6 on 2024-06-18 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0013_alter_subscription_options_subscription_featured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionprice',
            options={'ordering': ['subscription__order', 'order', 'featured', '-updated']},
        ),
    ]
